### ISSUE TITLE
One container per sha

### ISSUE THREAD

**Issue by samouri** [Automattic/dserve#20]
as of now, `dserve` creates a new container every time a request comes in for a branch that doesn't have a running container. We end up creates multiple containers for the same image.  On top of that, if for whatever reason the container fails to start properly, we will keep looping and create a ton of containers for that image.

Possible solutions:
1. always delete a container when we are done with it (that means after not being used for awhile or if it failed to start to begin with).
2. reuse existing stopped containers instead of starting new ones.

**Comment by blowery** [comment]
i think we might be able to close this? we're now better at finding running containers for an image, and we remove containers when we detect they're stale instead of just stopping them.
