### ISSUE TITLE
Uploading media not working on calypso.live on Chrome

### ISSUE THREAD

**Issue by alisterscott** [Automattic/dserve#69]
Steps to reproduce

1. Visit a calypso.live environment and open the editor  in Chrome- eg. https://hash-4ac8a178e189ab29733438e67887a3faa1049b74.calypso.live/post
2. Upload an image 

Image doesn't upload - endless spinner:

<img width="353" alt="screen shot 2018-10-24 at 11 17 44 am" src="https://user-images.githubusercontent.com/128826/47399945-624f1080-d77e-11e8-9204-53aba5276be3.png">

Tested fine on Safari and Firefox on macOS

**Comment by alisterscott** [comment]
Workaround in https://github.com/Automattic/wp-e2e-tests/pull/1552

**Comment by jsnajdr** [comment]
Should be fixed now after https://github.com/Automattic/wp-calypso/pull/28079 got merged.
